### PR TITLE
fix: use quote for IDs

### PR DESCRIPTION
**Pull request by laysent**
### What was a problem

There are several cases where quote should be used for IDs but didn't implement, such as:

1. When label is "node", it should be quoted, otherwise dot can't parse it correctly (i.e. `label = node` results in syntax error);
2. When label contains `.`, it should be marked in quote.

### How this PR fixes the problem

I think it might be safe to simply quote all IDs, no matter it's necessary or not.

### Check lists (check `x` in `[ ]` of list items)

- [x] Test passed
- [x] Coding style (indentation, etc)

### CODE REVIEW

**Comment by kamiazya** [comment]
@laysent 

Good job!

I want to release it as soon as the README output example is corrected.

Thanks.

**Comment by laysent** [comment]
@kamiazya README.md has been updated :-)

**Comment by kamiazya** [comment]
@laysent 
Thanks!
I will release it when I come home!

**Comment by kamiazya** [comment]
@all-contributors please add @laysent for bug and tests.

**Pull request merged**
